export const skills = [
    "Semantich & accessible HTML",
    "Error handling",
    "Git",
    "Responsive Web Design",
    "React",
    "Github Pull Requests & Review",
    // eslint-disable-next-line no-script-url
    "JavaScript: ES6+",
    "React Hooks",
    "NPM",
    "Working with API (fetch, axios)",
    "Redux (Toolkit)",
    "Immutability",
    "Promises, Asyns/Await",
    "Redux-Saga",
    "Markdown",
    "Debugging",
    "React Router",
    "Scrum",
    "CSS Flexbox",
    "CSS Grid",
    "Trello",
    "Teamwork",
    "CSS BEM convection",
];

export const nextSkills = [
    "JS classes",
    "Unit testing",
    "Node.js",
    "TypeScript",
    "Cypress",
    "React Context",
];